### ISSUE TITLE
Testing with jest

### ISSUE THREAD

**Issue by 3lrv-ryan** [tx2z/wc-base-typescript#21]
I really like what you've done here. I tried modifying this to use [jest](https://jestjs.io/) and couldn't figure out how to add a transform like what you did with the rollup preprocessing. Any suggestions? Would you be interested in this change as a PR?

**Comment by tx2z** [comment]
frack @3lrv-ryan sorry for not letting any message... I didn't see your original message and this past months have been crazy and I didn't check github.

I don't have so much experience with jest and no so much time to help, but I can try to take a look in January (things should be better) if you're still interested.

Oh, this is sad, I'm really sorry :(

**Comment by 3lrv-ryan** [comment]
No worries. I'm putting web components on hold for the time anyway. Happy holidays!
